runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:application

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  FLASK_ENV: 'production'
  FLASK_APP: 'app.py'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

